id: 504640a45a134a19b54a94a71c9f4470
initial_creation_type: ocr
source_metadata:
  volumes:
    b027bd7709ba4bf196e9cbfa09683faf:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: དབུ་མ་རྩ་བའི་འགྲེལ་པ་བུདྡྷ་པཱ་ལི་ཏ།
      total_pages: 1605
      volume_number: 57
